### ISSUE TITLE
Uncaught TypeError: XRegExp is not a function

### ISSUE THREAD

**Issue by zsedem** [ranjitjhala/linter-hdevtools#8]
I think the xregexp 3.1.0 is not compatible with your package

It simply throws this error after install

**Atom Version**: 1.6.0
**System**: "Arch Linux"
**Thrown From**: [linter-hdevtools](https://github.com/ranjitjhala/linter-hdevtools) package, v1.7.0
### Stack Trace

Uncaught TypeError: XRegExp is not a function

```
At /home/zsedem/.atom/packages/linter-hdevtools/lib/init.coffee:31

TypeError: XRegExp is not a function
    at infoErrors (/home/zsedem/.atom/packages/linter-hdevtools/lib/init.coffee:31:11)
    at BufferedProcess.exit (/home/zsedem/.atom/packages/linter-hdevtools/lib/init.coffee:105:23)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
  7x -0:07.9.0 blur (atom-text-editor.editor.is-focused.vim-mode-plus.normal-mode)
```
### Config

``` json
{
  "core": {},
  "linter-hdevtools": {
    "hdevtoolsUseStack": true
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-haskell, v0.6.3
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.2
autocomplete-snippets, v1.10.0
cursor-history, v0.5.9
ide-haskell, v1.5.4
ide-haskell-stack, v0.0.3
language-gherkin, v1.0.3
language-haskell, v1.7.5
linter, v1.11.4
linter-hdevtools, v1.7.0
linter-pep8, v1.2.1
linter-pylint, v1.2.0
vim-mode-plus, v0.25.0

# Dev
No dev packages
```

**Comment by paparent** [comment]
+1 I've the same issue

**Comment by ranjitjhala** [comment]
Hi, sorry for the delay -- I think simply adding an upper bound on the XRegExp dependency should fix this. Will do as soon as github starts functioning again!

**Comment by ranjitjhala** [comment]
Can you check if this is fixed in the latest version 1.9.0 ? Thanks!

**Comment by zsedem** [comment]
It is fixed, thanks

**Comment by mcheung63** [comment]
hey, my package also have problem. May i know how you fix this?
